apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  selector:
    matchLabels:
      app: dotnet-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: nlakaniplo/dotnet-app:latest
        ports:
        - containerPort: 5000
