apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp-deployment
  annotations:
    keburnetes.io/changes-cause: Initianal deployment of the app
spec:
  replicas: 5 # tells deployment to run 5 pods matching the template
  selector:
    matchLabels:
      app: dotnet-webapp
  template:
    metadata:
      name: dotnetappk8s
      labels:
        env: prod
        app: dotnet-webapp
        app.kubernetes.io/name: dotnet-webapp
    spec:
      containers:
        - name: dotnet-webapp
          image: nlakaniplok/dotnet-app:latest
          ports:
            - containerPort: 80
              name: http-web-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-services
spec:
  selector:
    app.kubernetes.io/name: dotnet-webapp
  ports:
    - name: dotnet-webapp-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
